# Generated by Django 3.1.2 on 2023-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_eglise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('lien_article', models.URLField(blank=True)),
                ('document_word', models.FileField(blank=True, max_length=254, upload_to=None)),
                ('document_pdf', models.FileField(blank=True, max_length=254, upload_to=None)),
            ],
        ),
    ]
