# Generated by Django 3.1.2 on 2023-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_article_paroissiale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_eglise',
            name='document_pdf',
            field=models.FileField(max_length=254, null=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='article_eglise',
            name='document_word',
            field=models.FileField(max_length=254, null=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='article_paroissiale',
            name='document_pdf',
            field=models.FileField(max_length=254, null=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='article_paroissiale',
            name='document_word',
            field=models.FileField(max_length=254, null=True, upload_to='public'),
        ),
    ]
