# Generated by Django 3.1.2 on 2023-03-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_auto_20230307_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_eglise',
            name='document_pdf',
        ),
        migrations.RemoveField(
            model_name='article_eglise',
            name='document_word',
        ),
    ]
