# Generated by Django 3.1.2 on 2023-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0008_auto_20230310_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_paroissiale_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('lien_article', models.URLField(blank=True)),
                ('document_pdf', models.FileField(blank=True, default='default.pdf', max_length=254, null=True, upload_to='public')),
            ],
        ),
        migrations.CreateModel(
            name='Article_paroissiale_pdf_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('lien_article', models.URLField(blank=True)),
                ('document_word', models.FileField(blank=True, default='default.doc', max_length=254, null=True, upload_to='public')),
                ('document_pdf', models.FileField(blank=True, default='default.pdf', max_length=254, null=True, upload_to='public')),
            ],
        ),
        migrations.CreateModel(
            name='Article_paroissiale_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('lien_article', models.URLField(blank=True)),
                ('document_word', models.FileField(blank=True, default='default.doc', max_length=254, null=True, upload_to='public')),
            ],
        ),
    ]
