
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home_view, name='home'),
    path('auth/', include('app_auth.urls'), name= 'connexion'),
    path('images_en_tete/', include('images_en_tete.urls')),
    path('annonces/', include('annonces.urls')),
    path('carousel/', include('carousel.urls')),
    path('galerie/', include('galerie.urls')),
    path('annonces', views.annonces, name='annonces'),
    path('faire_un_don', views.faire_un_don, name='faire_un_don'),
    path('actualites', views.actualites, name='actualites'),
    path('actualites_eglise', views.actualites_eglise, name='actualites_eglise'),
    path('actualites_paroissiale', views.actualites_paroissiale, name='actualites_paroissiale'),
    path('galerie', views.galerie, name='galerie'),
    path('horaire_messe', views.horaire_messe, name='horaire_messe'),
    path('contact', views.contact, name='contact'),
    path('infos_pratiques', views.infos_pratique, name='infos_pratique'),
    path('aller_au_kt', views.aller_au_kt, name='aller_au_kt'),
    path('histoire', views.histoire, name='histoire'),
    path('coquille', views.coquille, name='coquille'),
    path('liens_utils', views.liens_utils, name='liens_utils'),
    path('aller_au_kt', views.aller_au_kt, name='aller_au_kt'),
    path('aller_au_kt/eveil_a_la_foi', views.eveil_a_la_foi, name='eveil_a_la_foi'),
    path('aller_au_kt/cathéchisme_du_primaire', views.cathechisme_du_primaire, name='cathéchisme_du_primaire'), 
    path('aller_au_kt/cathechisme_6è_5è', views.cathechisme_6è_5è, name='cathechisme_6è_5è'),
    path('aller_au_kt/1ère_communion', views.communion, name='1ère_communion'),
    path('aller_au_kt/Aumonérie_jeunes', views.aumonerie_jeunes, name='aumonerie_jeunes'),
    path('aller_au_kt/parcours_confirmation', views.parcours_confirmation, name='parcours_confirmation'),
    path('aller_au_kt/pour_aller_loin', views.pour_aller_loin, name='pour_aller_loin'),
    path('vivre_en_eglise', views.vivre_en_eglise, name='vivre_en_eglise'), 
    path('vivre_en_eglise/guides_scouts_europe', views.guide_scouts, name='guide_scouts'),
    path('vivre_en_eglise/communauté_réligieuses', views.communaute_religieuse, name='communaute_religieuse'), 
    path('vivre_en_eglise/prier_celebrer', views.prier_celebrer, name='prier_celebrer'), 
    path('vivre_en_eglise/prier_celebrer/equipe_animation_liturgique', views.equipe_animation_liturgique, name='equipe_animation_liturgique'), 
    path('vivre_en_eglise/prier_celebrer/equipe_animation_paroissiale', views.equipe_animation_paroissiale, name='equipe_animation_paroissiale'),
    path('vivre_en_eglise/prier_celebrer/chorale', views.chorale, name='chorale'), 
    path('vivre_en_eglise/pour_en_aider', views.pour_en_aider, name='pour_en_aider'), 
    path('vivre_en_eglise/pour_sen_aider/conseil_economique_paroissiale', views.conseil_economique_paroissiale, name='conseil_economique_paroissiale'),
    path('vivre_en_eglise/pour_en_aider/dernier_de_eglise', views.dernier_de_eglise, name='dernier_de_eglise'), 
    path('vivre_en_eglise/pour_en_aider/secours_catholique', views.secours_catholique, name='secours_catholique'), 
    path('vivre_en_eglise/pour_en_aider/société_de_Saint_Vincent_de_Paul', views.société_saint_vincent_paul, name='société_saint_vincent_paul'), 
    path('vivre_en_eglise/pour_en_aider/CCFD', views.CCFD, name='CCFD'), 
     path('vivre_en_eglise/pour_en_aider/pour_sinformer', views.pour_sinformer, name='pour_sinformer'), 
    path('vivre_en_eglise/pour_en_aider/chantier_cardinal', views.chantier_cardinal, name='chantier_cardinal'), 
    path('celebrer', views.celebrer, name='celebrer'), 
    path('celebrer/bapteme', views.bapteme, name='bapteme'), 
    path('celebrer/eucharistie', views.eucharistie, name='eucharistie'),
    path('celebrer/confirmation', views.confirmation, name='confirmation'), 
    path('celebrer/Réconciliation', views.reconciliation, name='reconciliation'),
    path('celebrer/mariage', views.mariage, name='mariage'),   
    path('celebrer/sacrément_des_malades', views.sacrement_malade, name='sacrement_malade'),  
    path('celebrer/funérailles', views.funéraille, name='funéraille'), 
    path('celebrer/calendrier', views.calendrier, name='calendrier'), 
    path('prier', views.prier, name='prier'),
    path('prier/chapelet', views.chapelet, name='chapelet'), 
    path('prier/adoration', views.adoration, name='adoration'), 
    path('equipe_pastorale', views.equipe_pastorale, name='equipe_pastorale'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )
